spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/andras
    username: root
    password: andras
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true